# Generated by Django 4.2.6 on 2023-10-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsTaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=100)),
                ('shipper', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('transport_mode', models.CharField(max_length=100)),
                ('mawb_mbl', models.CharField(max_length=100)),
                ('hawb_hbl', models.CharField(max_length=100)),
                ('customs_release', models.BooleanField(default=False)),
                ('etd', models.DateTimeField()),
                ('eta', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
