# Generated by Django 4.2.6 on 2023-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogisticsTaskManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogisticsTaskManager',
        ),
        migrations.AlterField(
            model_name='shipmenttask',
            name='eta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipmenttask',
            name='etd',
            field=models.DateField(),
        ),
    ]
