# Generated by Django 4.2.6 on 2023-10-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogisticsTaskManager', '0002_delete_logisticstaskmanager_alter_shipmenttask_eta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmenttask',
            old_name='completed',
            new_name='arrived',
        ),
        migrations.AddField(
            model_name='shipmenttask',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
